apiVersion: v1
kind: ServiceAccount
metadata:
  name: roam-controller
  namespace: roam-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roam-controller
  name: job-manager
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roam-controller-job-manager
  namespace: roam-controller
subjects:
  - kind: ServiceAccount
    name: roam-controller
    namespace: roam-controller
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io
