[project]
name = "roam-worker"
version = "0.1.0"
description = "Persistent worker for ROAM remote execution"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["redis>=5.0.0", "celery>=5.3.0"]

[tool.uv]
dev-dependencies = ["ruff>=0.13.1"]
