[project]
name = "roam-controller"
version = "0.1.0"
description = "Controller for Run On Another Machine"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-cli>=0.0.13",
    "fastapi[standard]>=0.117.1",
]

[tool.uv]
dev-dependencies = ["ruff>=0.13.1"]
